/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/vue-query';
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType
} from '@tanstack/vue-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  unref
} from 'vue';
import type {
  MaybeRef
} from 'vue';

import type {
  UpdateEmailRequest,
  UpdatePasswordRequest,
  UpdateUsernameRequest
} from '.././model';





/**
 * Updates the password of the currently authenticated user.
 * @summary Update password
 */
export const updateUserPassword = (
    updatePasswordRequest: MaybeRef<UpdatePasswordRequest>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    updatePasswordRequest = unref(updatePasswordRequest);
    
    return axios.default.put(
      `/api/userinfo/password`,
      updatePasswordRequest,options
    );
  }



export const getUpdateUserPasswordMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserPassword>>, TError,{data: UpdatePasswordRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserPassword>>, TError,{data: UpdatePasswordRequest}, TContext> => {
    
const mutationKey = ['updateUserPassword'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserPassword>>, {data: UpdatePasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateUserPassword(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserPassword>>>
    export type UpdateUserPasswordMutationBody = UpdatePasswordRequest
    export type UpdateUserPasswordMutationError = AxiosError<string>

    /**
 * @summary Update password
 */
export const useUpdateUserPassword = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserPassword>>, TError,{data: UpdatePasswordRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateUserPassword>>,
        TError,
        {data: UpdatePasswordRequest},
        TContext
      > => {

      const mutationOptions = getUpdateUserPasswordMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Retrieves the username of the currently authenticated user.
 * @summary Get username
 */
export const getUserName = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.get(
      `/api/userinfo/name`,options
    );
  }


export const getGetUserNameQueryKey = () => {
    return ['api','userinfo','name'] as const;
    }

    
export const getGetUserNameQueryOptions = <TData = Awaited<ReturnType<typeof getUserName>>, TError = AxiosError<string>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserName>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getGetUserNameQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserName>>> = ({ signal }) => getUserName({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserName>>, TError, TData> 
}

export type GetUserNameQueryResult = NonNullable<Awaited<ReturnType<typeof getUserName>>>
export type GetUserNameQueryError = AxiosError<string>


/**
 * @summary Get username
 */

export function useGetUserName<TData = Awaited<ReturnType<typeof getUserName>>, TError = AxiosError<string>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserName>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserNameQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}



/**
 * Updates the username of the currently authenticated user.
 * @summary Update username
 */
export const updateUserName = (
    updateUsernameRequest: MaybeRef<UpdateUsernameRequest>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    updateUsernameRequest = unref(updateUsernameRequest);
    
    return axios.default.put(
      `/api/userinfo/name`,
      updateUsernameRequest,options
    );
  }



export const getUpdateUserNameMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserName>>, TError,{data: UpdateUsernameRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserName>>, TError,{data: UpdateUsernameRequest}, TContext> => {
    
const mutationKey = ['updateUserName'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserName>>, {data: UpdateUsernameRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateUserName(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserNameMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserName>>>
    export type UpdateUserNameMutationBody = UpdateUsernameRequest
    export type UpdateUserNameMutationError = AxiosError<string>

    /**
 * @summary Update username
 */
export const useUpdateUserName = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserName>>, TError,{data: UpdateUsernameRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateUserName>>,
        TError,
        {data: UpdateUsernameRequest},
        TContext
      > => {

      const mutationOptions = getUpdateUserNameMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Retrieves the email address of the currently authenticated user.
 * @summary Get user email
 */
export const getUserEmail = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.get(
      `/api/userinfo/email`,options
    );
  }


export const getGetUserEmailQueryKey = () => {
    return ['api','userinfo','email'] as const;
    }

    
export const getGetUserEmailQueryOptions = <TData = Awaited<ReturnType<typeof getUserEmail>>, TError = AxiosError<string>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserEmail>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  getGetUserEmailQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserEmail>>> = ({ signal }) => getUserEmail({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserEmail>>, TError, TData> 
}

export type GetUserEmailQueryResult = NonNullable<Awaited<ReturnType<typeof getUserEmail>>>
export type GetUserEmailQueryError = AxiosError<string>


/**
 * @summary Get user email
 */

export function useGetUserEmail<TData = Awaited<ReturnType<typeof getUserEmail>>, TError = AxiosError<string>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserEmail>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserEmailQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>;

  return query;
}



/**
 * Updates the email address of the currently authenticated user.
 * @summary Update email
 */
export const updateUserEmail = (
    updateEmailRequest: MaybeRef<UpdateEmailRequest>, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    updateEmailRequest = unref(updateEmailRequest);
    
    return axios.default.put(
      `/api/userinfo/email`,
      updateEmailRequest,options
    );
  }



export const getUpdateUserEmailMutationOptions = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserEmail>>, TError,{data: UpdateEmailRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateUserEmail>>, TError,{data: UpdateEmailRequest}, TContext> => {
    
const mutationKey = ['updateUserEmail'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUserEmail>>, {data: UpdateEmailRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateUserEmail(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserEmailMutationResult = NonNullable<Awaited<ReturnType<typeof updateUserEmail>>>
    export type UpdateUserEmailMutationBody = UpdateEmailRequest
    export type UpdateUserEmailMutationError = AxiosError<string>

    /**
 * @summary Update email
 */
export const useUpdateUserEmail = <TError = AxiosError<string>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUserEmail>>, TError,{data: UpdateEmailRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationReturnType<
        Awaited<ReturnType<typeof updateUserEmail>>,
        TError,
        {data: UpdateEmailRequest},
        TContext
      > => {

      const mutationOptions = getUpdateUserEmailMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    