/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Category information response
 */
export interface CategoryResponseDTO {
  /** Category ID */
  id?: number;
  /** Category name */
  name?: string;
}
