/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Item } from './item';

export interface Category {
  id?: number;
  name?: string;
  items?: Item[];
}
