/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user';
import type { Item } from './item';

export interface Favorite {
  id?: number;
  user?: User;
  item?: Item;
  dateAdded?: string;
}
