/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Item status
 */
export type ItemResponseDTOStatus = typeof ItemResponseDTOStatus[keyof typeof ItemResponseDTOStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemResponseDTOStatus = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  SOLD: 'SOLD',
  RESERVED: 'RESERVED',
} as const;
