/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ItemStatus = typeof ItemStatus[keyof typeof ItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemStatus = {
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
  SOLD: 'SOLD',
} as const;
