/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponse } from './userResponse';
import type { ItemResponseDTO } from './itemResponseDTO';

/**
 * Message information response
 */
export interface MessageResponseDTO {
  /** Message ID */
  id?: number;
  sender?: UserResponse;
  receiver?: UserResponse;
  item?: ItemResponseDTO;
  /** Message content */
  content?: string;
  /** Message timestamp */
  timestamp?: string;
}
