/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user';
import type { Item } from './item';
import type { OrderStatus } from './orderStatus';

export interface Order {
  id?: number;
  buyer?: User;
  item?: Item;
  orderDate?: string;
  status?: OrderStatus;
  paymentMethod?: string;
  transactionId?: string;
}
