/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Request payload for updating email
 */
export interface UpdateEmailRequest {
  /**
   * The new desired email address
   * @minLength 0
   * @maxLength 100
   */
  email: string;
}
