/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Request payload for updating password
 */
export interface UpdatePasswordRequest {
  /**
   * The new desired password
   * @minLength 6
   * @maxLength 2147483647
   */
  password: string;
}
