/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Request payload for updating username
 */
export interface UpdateUsernameRequest {
  /**
   * The new desired username
   * @minLength 3
   * @maxLength 50
   */
  username: string;
}
