/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Request payload for updating password
 */
export interface UpdatePasswordRequest {
  /** The current password for verification */
  currentPassword: string;
  /**
   * The new desired password
   * @minLength 8
   * @maxLength 2147483647
   */
  newPassword: string;
}
