/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserRole } from './userRole';
import type { Item } from './item';
import type { Favorite } from './favorite';
import type { Order } from './order';
import type { GrantedAuthority } from './grantedAuthority';

export interface User {
  /**
   * @minLength 3
   * @maxLength 20
   */
  username: string;
  email: string;
  /**
   * @minLength 6
   * @maxLength 2147483647
   */
  password: string;
  role?: UserRole;
  items?: Item[];
  favorites?: Favorite[];
  orders?: Order[];
  enabled?: boolean;
  authorities?: GrantedAuthority[];
  accountNonLocked?: boolean;
  accountNonExpired?: boolean;
  credentialsNonExpired?: boolean;
  displayUsername?: string;
}
