/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserResponseRole } from './userResponseRole';

/**
 * User information response
 */
export interface UserResponse {
  /** User ID */
  id?: number;
  /** Username */
  username?: string;
  /** Email address */
  email?: string;
  /** User role */
  role?: UserResponseRole;
}
