/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * User role
 */
export type UserResponseRole = typeof UserResponseRole[keyof typeof UserResponseRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseRole = {
  ADMIN: 'ADMIN',
  USER: 'USER',
} as const;
